apiVersion: v1
kind: Service
metadata:
  name: selenium-node
  namespace: test-grid
  namespace: test-grid
  labels:
    name: grid-services
    app: grid

spec:

  selector:
    name: hub-pod
    app: grid

  ports:
    - port: 4442
      targetPort: 4442
      name: port2

    - port: 4443
      targetPort: 4443
      name: port1